config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: "sessions#create"
  get '/auth/failure', to: redirect('/')
  get '/signout', to: "sessions#destroy", as: :signout

  get '/user', to: "users#show"
  get '/user/repos', to: "repos#index" #/repos/user?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_organization.rb
class GithubOrganization
  attr_reader :name

  def initialize(org)
    @name = org[:login]
  end

  def self.all(token)
    GithubService.new(token).organizations.map { | org | GithubOrganization.new(org) }
  end

end

app/models/github_repo.rb
class GithubRepo
  attr_reader :name

  def initialize(repo)
    @name = repo[:name]
  end

  def self.all(token)
    GithubService.new(token).repos.map { |repo| GithubRepo.new(repo) }
    #returns an array of hashes so we have to turn each hash into an object
  end

  def self.starred(token)
    GithubService.new(token).starred
    # should return an array of repos that are starred
  end

end








# def self.service(token)
#   @service ||= GithubService.new(token)
# end (:service in attr_reader too)

app/models/github_user.rb
class GithubUser
  # 
  # def initialize
  #
  # end

  def self.followers(token)
    GithubService.new(token).followers.map { |follower| GithubUser.new }
      #should return an array of followers.count
  end

  def self.following(token)
    GithubService.new(token).following.map { |following| GithubUser.new }
    #should return an array of users following you.count
  end



end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_hash)
    where(uid: auth_hash[:uid]).first_or_create do |new_user|
      new_user.provider           = auth_hash.provider
      new_user.uid                = auth_hash.uid
      new_user.name               = auth_hash.info.name
      new_user.username           = auth_hash.info.nickname
      new_user.oauth_token        = auth_hash.credentials.token
      new_user.oauth_token_secret = auth_hash.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    @repos = GithubRepo.all(current_user.oauth_token)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(auth_hash)
      session[:user_id] = user.id
    end
      redirect_to user_path, notice: "Logged in successfully!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You have successfully logged out."
  end

  private
  def auth_hash
    request.env["omniauth.auth"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @repo_count = GithubRepo.starred(current_user.oauth_token).count
    @repos = GithubRepo.all(current_user.oauth_token)
    @followers = GithubUser.followers(current_user.oauth_token).count
    @following = GithubUser.following(current_user.oauth_token).count
    @orgs = GithubOrganization.all(current_user.oauth_token)
    # byebug
  end

  def create
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      format.html { redirect_to(@user, notice: 'User was successfully created.') }
      format.json { render json: @user, status: :created, location: @user }
    else
      format.html { render action: 'new' }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<% if current_user %>
Welcome, <%= current_user.name %>
<% else %>
Hello! Please log in.
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2017 GutHub, Inc.
    <a href="#">Terms</a>
    <a href="#">Privacy</a>
    <a href="#">Security</a>
    <a href="#">Status</a>
    <a href="#">Help</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">API</a></li>
      <li><a href="#">Training</a></li>
      <li><a href="#">Shop</a></li>
      <li><a href="#">Blog</a></li>
      <li><a href="#">About</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabyGit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "BabyGit", '/', id: "logo" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div id="right">
            <form class="navbar-form navbar-left" role="search">
                <input type="text" class="form-control" placeholder="Search">
              <input type="hidden">
            </form>
          <ul class="nav navbar-nav">
            <li><a href="#">Pull requests</a></li>
            <li><a href="#">Issues</a></li>
            <li><a href="#">Gist</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login with Github", github_login_path unless current_user %><%= link_to "Logout", signout_path if current_user %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Your profile", user_path %></li>
                <li><a href="/user/repos">Your repositories</a></li>
                <!-- <li><a href="#">Your stars</a></li> -->
                <li><a href="#">Explore</a></li>
                <li><a href="#">Integrations</a></li>
                <li><a href="#">Help</a></li>
                <li class="divider"></li>
                <li><a href="#">Settings</a></li>
              </ul>
            </li>
          </ul>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
        <br><br>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/repos/index.html.erb
<h1><%= current_user.name %>'s Repositories</h2>
<% @repos.each do |repo| %>
<%= repo.name %><br>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
    <div class="row">
      <!-- <div class="col-md-5" id="profile"> -->
        <div class="col-md-3" class="card" style="width: 25rem;" id="profile">
          <%= image_tag "https://avatars2.githubusercontent.com/u/#{current_user.uid}?v=3&amp;s=220" %>
          <div class="card-block">
            <h4 class="card-title">Welcome, <%= current_user.name %>!</h4>
            <p class="card-text">Username: <%= current_user.username %></p>
            <p class="card-text">You have <b><%= @followers %></b> followers.</p>
            <p>You are following <b><%= @following %></b> other users.</p>
          </div>
        </div>

        <div class="col-md-2" style="width: 10rem;">
          <div class="card-block">
            <h4 class="card-title"></h4>
            <p class="card-text" align="left"></p>
          </div>
        </div>

        <!-- begin tabbed section -->
        <div class="col-md-7" class="card text-center" id="toggle">
          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#repo">My Repositories</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#orgs">My Organizations</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#feeds">My Activity Feeds</a>
              </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">

              <div class="tab-pane active" id="repo" role="tabpanel">
                <h4 class="card-title">Repository Stats</h4>
                <p class="card-text"><p>Starred: <%= @repo_count %></p>
                <p>Total: <%= @repos.count %></p></p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <a href="/user/repos" class="btn btn-primary">Repository details</a>
              </div>

              <div class="tab-pane" id="orgs" role="tabpanel">
                <h4 class="card-title">Organizations</h4>
                <p class="card-text"><p>View a list of organizations to which i belong.</p>
                <p><%#= @orgs.first.name %></p>
                <p><%#= @orgs.last.name %></p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              </div>

              <div class="tab-pane" id="feeds" role="tabpanel">
                <h4 class="card-title">My Recent Activity</h4>
                <p class="card-text"><p>View a summary feed of my recent activity (recent commits)</p>
                <hr>
                <h4 class="card-title">My Recent Activity</h4>
                <p>View a summary feed of recent activity from users whom I follow</p>
                <hr>
              </div>
            </div>
          </div>
        </div>
        <!-- end tabbed section -->
      </div>
    </div>